[project]
name = "telegram-bot"
version = "1.0.0"
dependencies = [
    "python-telegram-bot==13.15",  # IMPORTANT: Correct package
    "requests==2.31.0",
    "Faker==24.3.0",
    "tqdm==4.66.2"
]

[build-system]
requires = ["uv"]
build-backend = "uv.build_backend"
